import {environment} from '../../environments/environment';
export const STR_CONST = {
  complete_daily_win: 'Compete Daily & Win',
  continue_with_fb: 'CONTINUE WITH FACEBOOK',
  sign_up_with_email: 'SIGN UP',
  sign_up: 'Sign up',
  blank_email_error: 'Please enter your Email',
  invalid_email_error: 'Please enter a valid Email Address',
  blank_password_error: 'Please enter your password',
  forgot_password: 'Forgot Your Password?',
  sign_in: 'SIGN IN',
  password: 'Password ',
  show: 'SHOW',
  hide: 'HIDE',
  sign_out: 'Log Out',
  profile: 'Profile',
  log_in: 'LOG IN',
  dreamPick: 'DreamPick',
  logoutText: 'Are you sure you want to sign out of DreamPick?',
  enter_your_email: 'Enter Your Email',
  enter_your_password: 'Enter Your Password',
  promo_code: 'Promo Code(Optional)',
  next: 'Next',
  email_subtitle: "You'll use this to log in to your account",
  full_name: 'Full Name',
  full_name_title: 'Enter Your Name',
  full_name_sub_title:
    "Your name should match either your Driver's License or Passport",
  you_reached_max_limit: 'You have reached the maximum limit of',
  you_reached_max_limit_two: 'entries. Please select another contest',
  first_name: 'First Name',
  last_name: 'Last Name',
  blank_first_name_error: 'Please enter your First Name',
  blank_last_name_error: 'Please enter your Last Name',
  user_name: 'Username',
  user_name_title: 'Create a Username',
  user_name_sub_title: 'This is how you will appear in contests',
  user_name_specification: 'It must be 4-20 characters long with no spaces.',
  user_name_blank_error: 'Please enter a valid Username',
  user_name_less_than_four_digit_error:
    'Your Username must be greater than 3 characters',
  user_name_greater_than_twenty_digit_error:
    'Your username must be less than 21 character',
  user_name_space_error: 'Your Username must not contain spaces',
  state_header: 'State/Province',
  state_title: 'Select Your Location',
  state_sub_title:
    "We'll use this information to comply with local laws related to playing Daily Fantasy Sports.",
  state: 'State',
  state_error: 'Please select a state',
  password_sub_title:
    'Your password must include one number, one letter, and be 8-20 characters long.',
  account_title: 'CREATE ACCOUNT',
  password_error: 'Please enter your Password',
  invalid_password_error: 'Please enter a valid Password',
  privacy_error: 'Please agree to the Terms of Use and Privacy Policy',
  password_sub:
    'I agree to the Terms Of Use and Privacy Policy. I confirm that I am at least 18 years of age. Must be 19 years of age in NE. Must be 21 years of age in MA.',
  gps_btn_text: 'OK',
  gps_skip_btn_text: 'Not Now',
  gps_title: 'Fetching Location',
  gps_info:
    "Allow DreamPick to turn on your phone's GPS for\naccurate location.",
  dob_header: 'Birthday',
  dob_place_holder: 'MM | DD | YYYY',
  dob_title: 'Enter Your Birthday',
  dob_sub_title: "Let's check and see if you're old enough to play",
  dob_blank_error: 'Please enter your Birthday',
  dob_eligibility_error:
    'You must be at least 18 years old to participate in DreamPick',
  dob_eligibility_error_NE:
    'You must be at least 19 years old to participate in DreamPick',
  dob_eligibility_error_MA:
    'You must be at least 21 years old to participate in DreamPick',
  dob_picker_guide:
    'All the users must be at least 18 years of age to play. Some jurisdictionsrequire users to be older.',
  email_bottom_title:
    'We collect information that you provide to DreamPick. Our Privacy Policy governs how we use your information.',
  deposit_title: 'Make a Deposit',
  deposit_description:
    'Add Funds and Start Competing for Cash Prizes Immediately',
  deposit: 'DEPOSIT',
  offer_ends_soon: 'OFFER ENDS SOON',
  continue: 'Continue',
  howToPlayHeader: 'How to Play',
  howToPlayList: [
    {
      title: 'Ways to Play',
    },
    {
      title: 'Find Contests',
    },
    {
      title: 'Drafting a Lineup',
    },
  ],
  howToPlayInfo: 'Get tips and recommendations on how to play:',
  blank_valid_last_name_error: 'Please enter valid last name',
  blank_valid_first_name_error: 'Please enter valid first name',
  filter_title: 'Filter',
  filter_apply: 'Apply',
  filter_reset: 'Reset',
  all_title: 'All',
  filter_sub_title: 'Contests',
  sortby_title: 'Sort By',
  recommendation: 'Recommended',
  headtohead: 'Head to Head',
  contestType: 'Contest Type', //b
  multiEntry: 'Multi-Entry Limit', //b
  guranteedStatus: 'Guaranteed Status', //b
  enterCrown: 'Enter with Crowns',
  enterTicket: 'Enter with Tickets',
  enterContest: 'Enter with Contests',
  maxEnter: 'Include Max Entered',
  entryFree: 'Entry Free',
  gameCenter: 'Contest Details',
  entryBtn: 'Add Entry',
  otherEntryBtn: 'Add Another Entry',
  launch_title: '*Make your dreams come true in 4 steps.*',
  launch_sub_title:
    'Select a Sport ---> Select a Date ---> Join a Tournament ----> Select Team',
  email: 'Email',
  email_address: 'email-address',
  forgot_password_title: 'Forgot Password?',
  submit: 'SUBMIT',
  submitSmall: 'Submit',
  review: 'REVIEW',
  reviewSelection: 'Review Selections',
  viewSelection: 'Your Selections',
  cancel: 'CANCEL',
  hi: 'Hi, ',
  skip_caps: 'SKIP',
  next_caps: 'NEXT',
  finish_caps: 'FINISH',
  emailAddress: 'Email Address',
  createAccount: 'Create Account',
  cancelDeposit: 'Cancel Deposit?',
  areYouSure: 'Are you sure?',
  yes: 'YES',
  no: 'NO',
  checkingLocation: 'Checking your location',
  select: '- Select - ',
  reset_password: 'Please enter your Email address',
  done: 'Done',
  location_title: 'Location',
  learnMore: 'Learn More',
  searchContest: 'Search Contest',
  sports: 'Sports',
  noContest: 'You have not joined any contests at this time.',
  totalPrize: 'Prizes',
  entrants: 'Entrants',
  entries: 'Entry',
  myEntry: 'My Entries',
  inProgress: 'In Progress',
  Completed: 'Completed',
  starts: 'Starts: ',
  STARTS: 'STARTS: ',
  started: 'Started: ',
  entered: 'Contests Entered: ',
  all: 'All',
  ALL: 'ALL',
  nfl: 'NFL',
  NBA: 'NBA',
  NHL: 'NHL',
  MLB: 'MLB',
  myContest: 'My Contests',
  editEntry: 'Edit Entry',
  liveEntry: 'Live Entry',
  editEntries: 'Edit Entries',
  liveEntries: 'Live Entries',
  entryFee: 'Entry Fee',
  entries_label: 'Entries',
  placePaid: 'Places paid',
  totalPrize_label: 'Total Prizes',
  youPlaced: 'You Placed',
  ENTRANTS: 'ENTRANTS',
  ENTRIES: 'ENTRIES',
  DETAILS: 'DETAILS',
  noEntrantYet: 'There are no entrants available at this time.',
  noNotificationYet: 'There are no notification available at this time.',
  congratulations: 'Congratulations',
  yourPosition: 'Your Position :',
  winnings: 'Total Winnings: ',
  winningsLable: 'Winnings: ',
  selectSport: 'Select a Sport',
  contestTitle: 'Select Contest',
  contestTypeTitle: 'Select Contest Type',
  settings: 'Settings',
  myProfile: 'My Profile',
  notification: 'Notifications',
  pushNotification: 'Push Notifications',
  allowNotifications: 'Allow Notifications?',
  allowNotificationsDesc:
    'Stay informed on upcoming contests,\nresults and other relevant information.',
  notificationsAlertTitle: 'Allow Notifications',
  notificationsAlertDesc: 'Please allow Notifications in your Settings',
  contactUs: 'Contact Us',
  min: 'Min',
  max: 'Max',
  results: 'Results',
  outOf: 'Out Of',
  completedOn: 'Completed:',
  wallet: 'Wallet',
  noTournamentYet:
    'There are no contests available for those filter terms. Please try again.',
  noResultYet: 'There are no results available at this time.',
  viewRoster: 'View Roster',
  roster: 'ROSTER',
  stats: 'STATS',
  ENTRY: 'ENTRY',
  booster: 'BOOSTER:',
  est: 'EST FPPG',
  ep: 'EST POINTS',
  estOnly: 'EST',
  actual: 'ACTUAL',
  bonus: 'Bonus',
  bonusCap: 'BONUS',
  bonus_set: 'Bonus Set',
  gain: 'Gain',
  selected: 'SELECTED',
  SELECT: 'SELECT',
  threshold: 'THRESHOLD',
  points_needed: 'FANTASY PTS NEEDED',
  fantasyPoints: 'Fantasy Points',
  ff: 'Estimated Fantansy Points',
  i1: 'is estimated to score',
  i2: 'How confident are you about',
  i3: 'confident in selecting',
  you: 'You are',
  i4: 'Minimum fantasy points required by',
  scores: 'scores',
  less: 'less than',
  total: 'Total = ',
  totalCaps: 'TOTAL',
  lose: 'Lose',
  forEveryPoint: 'for every 1 point',
  losePercent: '2%',
  sub: 'will be subtracted',
  starter: 'starter',
  reserve: 'reserve',
  payoutStructure: 'Payout Structure',
  noCompleteYet: 'Please visit My Contests for updates.',
  scoringRule: 'Scoring Rules',
  noEntriesYet: 'No Entries Yet',
  standings: 'STANDINGS',
  entrantList: 'Entrants List',
  fairPlayCommitment: 'Fair Play Commitment',
  final: 'FINAL',
  entryDetail: 'Entry Details',
  noPlayerYet: 'No Players Yet',
  thresholdV: 'Threshold Fantasy Points',
  threePassingTd: '3 Passing Touchdowns',
  onePassingTd: '1 Rushing Touchdowns',
  twoPassingTd: '290 Passing Yards',
  rushing: '13 Rushing Yards',
  details: 'Details',
  wining: 'WINNING',
  FPG: 'FPTS',
  tooltipSelectContestTitle: 'Select from the list',
  tooltipSelectContestDescription: 'Join any contest listed below.',
  tooltipSelectContestTypeTitle: 'Select from the list',
  tooltipSelectContestTypeDescription:
    'Select the type of contest you wish to play',
  tooltipChooseTeamTitle: 'Choose 5 teams',
  tooltipChooseTeamDescription:
    'Select your teams by clicking on the Team Name',
  tooltipAddTeamTitle: 'Add',
  tooltipAddTeamDescription: 'Add a team by clicking the + sign',
  tooltipConfidenceTitle: 'Confidence Booster',
  tooltipConfidenceDescription:
    'Move the slider to indicate your level of confidence',
  dontHaveAccount: "Don't have an account?",
  addFunds: 'Add Fund',
  confidenceTeam: 'Team Selected',
  confidenceEstimatedPoints: 'Estimated Fantasy Pts',
  confidenceBonus: 'Earn Bonus',
  confidencePointsNeeded: 'Fantasy Pts Needed',
  confidenceFooter:
    'if your team misses the fantasy points needed,\n' +
    'you score a penalty of 2% per fantasy point missed.',
  confidenceChooseBonus: 'CHOOSE BONUS',
  confidenceSetBonus: 'SET BONUS',
  pos: 'POS',
  player: 'PLAYER',
  dtickText: 'POINTS USED',
  coldText: 'COLD',
  flameText: 'HOT',
  pp1Text: 'PRE SELECTED PLAYER',
  pp2Text: 'RESERVE PLAYER',
  ht:
    'Player/Team scored more than their estimated fantasy points for this game.',
  ct:
    'Player/Team scored less than their estimated fantasy points for this game.',
  ppt: "Player's fantasy points have counted towards this team's total.",
  pps:
    'Player is part of the main pre-selected roster. If he plays, his fantasy points will count towards the team.',
  ppj:
    'Player is an extra/reserve. His score is only used if a main/pre-selected player is injured or does not play.',
  dummyText:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  selectPicture: 'Choose from library',
  takePicture: 'Take a picture',
  cancelSmall: 'Cancel',
  noContestType:
    'Currently, there are no contests available in this category. Please try again later.',
  MENU_ITEMS: {
    IDS: {
      contact_us: 0,
      faq: 1,
      add_funds: 2,
      withdraw_funds: 3,
      transaction_history: 4,
      terms_condition: 5,
      privacy_policy: 6,
      rules_scoring: 7,
      fair_play_commitment: 8,
      responsible_gaming: 9,
      logout: 10,
      profile: 11,
    },
    TITLES: {
      contact_us: 'Contact Us',
      faq: 'FAQ',
      add_funds: 'Add Funds',
      withdraw_funds: 'Withdraw Funds',
      transaction_history: 'Transaction History',
      terms_condition: 'Terms and Conditions',
      privacy_policy: 'Privacy Policy',
      rules_scoring: 'Rules & Scoring',
      fair_play_commitment: 'Fair Play Commitment',
      responsible_gaming: 'Responsible Gaming',
      logout: 'Log Out',
      profile: 'Profile',
    },
    URI: {
      contact_us: `${environment.web_url}contact/?inapp=true `,
      faq: `${environment.web_url}faqs/?inapp=true `,
      terms_condition: `${environment.web_url}terms-and-conditions/?inapp=true`,
      privacy_policy: `${environment.web_url}privacy-policy/?inapp=true`,
      rules_scoring: `${environment.web_url}rules-scoring/?inapp=true`,
      fair_play_commitment: `${environment.web_url}fairplay-commitment/?inapp=true`,
      responsible_gaming: `${environment.web_url}responsible-gaming/?inapp=true`,
    },
  },
  transaction_history: 'Transaction History',
  date: 'DATE',
  type: 'TYPE',
  description: 'DESCRIPTION',
  amount: 'AMOUNT',
  filter_caps: 'FILTER',
  ok: 'OK',
  est_fantasy_points: 'EST Fantasy Pts',
  fantasy_points_needed: 'FANTASY PTS NEEDED',
  noNetworkTitleText: 'No Internet Connection',
  noNetworkDesText: `You phone is not connected to the internet.
  Please connect to a cellular or Wi-Fi network to
  continue using the DreamPick app.`,
  app_version: 'App Version',
  location_access: 'Location Access',
  location_services: 'Location Services',
  verify_your_location: 'Verify your Location',
  location_service_off_des:
    'Location Services must be enabled in order to use the DreamPick App.',
  location_service_off_des_two:
    'To enable Location Services, follow these steps:',
  open_setting_to_enable: 'OPEN SETTINGS',
  verify_location_step1:
    'To join contests in DreamPick, we are required to verify your location.',
  verify_location_step2:
    'Tap Allow when prompted on the next screen. This allows us to verify your location and if you can play daily fantasy sports.',
  GUARANTEED_HEADER_TEXT: 'GUARANTEED',
  GUARANTEED_DESCRIPTION_TEXT:
    'Guaranteed contests will run even if all entries are not filled.',
  withdraw_funds_title: 'Withdrawals',
  withdraw_funds_top_des:
    "Enter the amount you'd like to withdraw from your credit below. Our member relations team will process your request within 24-48 hours and contact you with an update.",
  total_balence: 'Total Balance',
  available_to_withdraw: 'Available To Withdraw',
  bonus_balance: 'Bonus Balance',
  withdraw_amnt: 'Withdrawal Amount',
  send_request_button: 'SEND REQUEST',
  middle_des0:
    '1x playthrough of deposit & promo is required before withdrawal.',
  middle_des1: 'Minimum withdrawal amount is $',
  middle_des2_1: 'Maximum withdrawal amount is $',
  middle_des2_2: ' per week',
  middle_des3:
    'Withdrawals are processed using e-check & are processed Monday through Friday from 1pm to 5pm eastern time',
  middle_des4:
    'After a e-check is initiated, funds will arrive in your bank account within 24-48 hours.',
  your_withdraw_req: 'Your Withdrawal Requests',
  status: 'STATUS',
  withdraw_funds_button: 'WITHDRAW FUNDS',
  android: 'android',
  cancelled: 'Cancelled',
  contestCancelled: 'Contest Cancelled',
  refund: 'Refund: ',
  emptyResultsLabel1: 'Your search term "',
  emptyResultsLabel2: '" did not fetch any results. Please try again.',
  emptyMyContestLabel2:
    '" did not fetch any contests that you have entered. Please try again.',
  emptyTournamentsLabel2: '" did not not fetch any contests.',
  selectedRosterPlayerIns:
    'Player is part of the main pre-selected roster. If he plays, his fantasy points will count towards the team.',
  reservedRosterPlayerIns:
    'Player is an extra/reserve. His score is only used if a main/pre-selected player is injured or does not play.',
  selectionBottomText:
    'if your team misses the fantasy points selected, you score a penalty of 2% per fantasy point missed.',
  reviewSelectionHeaderText: "Select Your Team's Fantasy Points",
  cameraAlertTitle: 'Allow Camera Access',
  cameraAlertDesc: 'Please allow Camera Access in your Settings',
  photoAlertTitle: 'Allow Photo Access',
  photoAlertDesc: 'Please allow Photos Access in your Settings',
  photoAlertDescAndroid:
    'Please allow Photos, Media & Files Access in your Settings',
  selectedFPTS: 'SELECTED FANTASY PTS ',
  projectedFantasyPoints: 'Projected Fantasy PTS',
  clickHere: 'Click here',
  availableStateDesc:
    'DreamPick is offered to legal residents physically located in 23 states.',
  availableStateDesc2:
    ' for the list of the states where DreamPick is offered.',
  availableStatePopupDesc:
    'DreamPick is offered to legal residents physically located in these 23 states',
  liveLeaderboard: 'Live Leaderboard',
  live: 'Live',
  LIVE: 'LIVE',
  penalty: 'Penalty',
  penaltyCaps: 'PENALTY',
  maxEntries: 'Max Entries',
  pay: 'pay',
  proj: 'PROJ',
  PRIZES_GTD: 'PRIZES(GTD)',
  gotIt: 'Got it!',
  UPCOMING: 'UPCOMING',
  TEAMS_PER_ENTRY: 'TEAMS PER ENTRY',
  noEntrantsJoinedYet: 'No entrants joined yet.',
  limitedTimeOnly: 'Limited Time Only',
  preSelectedRoster:
    'Player is part of the main pre-selected roster. If he plays, his fantasy points will count towards the team.',
  PROJECTED_FANTASY_POINTS: 'PROJECTED FANTASY POINTS',
  SELECT_TEAM: 'SELECT TEAM',
  SELECTED_FANTASY_PTS: 'SELECTED FANTASY PTS:',
  PROJ_POINTS: 'PROJ POINTS',
  chooseDiffPassword:
    'Password cannot contain Username. Please choose a different Password',
  privacy_policy: 'Privacy Policy',
  searchTransactions: 'Search Transactions',
  PROJ_FANTASY_PTS: 'PROJ FANTASY PTS',
  noWithdrawalRequestYet: 'No Withdrawal Request Yet',
  information: 'Information',
  howManyPoint: 'How Many Fantasy Points Will',
  score: 'Score ?',
  toDo: 'Placeholder Text - To Do',
  inPrizes: 'IN PRIZES',
  Games: 'Games',
  TEAMS: 'TEAMS',
  ChooseYourDate: 'Choose your date',
  ifYourTeamMiss:
    'if your team misses the fantasy points selected,you score a penalty of 2% per fantasy point missed.',
  LastPlay: 'Last Play: Travis Kelce 34 Yd pass from Patrick Mahomes',
};
