import {Platform} from 'react-native';
import * as CONST from '../constants';
import {Icons} from '../../assets/svg';
import {STR_CONST} from 'string_const';
export default {
  drawer: [
    {
      id: STR_CONST.MENU_ITEMS.IDS.profile,
      icon: CONST.PROFILE_USER,
      title: STR_CONST.MENU_ITEMS.TITLES.profile,
      uri: STR_CONST.MENU_ITEMS.URI.profile,
    },
    {
      id: STR_CONST.MENU_ITEMS.IDS.contact_us,
      icon: CONST.CALL,
      title: STR_CONST.MENU_ITEMS.TITLES.contact_us,
      uri: STR_CONST.MENU_ITEMS.URI.contact_us,
    },
    {
      icon: CONST.FAQ,
      id: STR_CONST.MENU_ITEMS.IDS.faq,
      title: STR_CONST.MENU_ITEMS.TITLES.faq,
      uri: STR_CONST.MENU_ITEMS.URI.faq,
    },
    {
      icon: CONST.ADD_FUNDS,
      id: STR_CONST.MENU_ITEMS.IDS.add_funds,
      title: STR_CONST.MENU_ITEMS.TITLES.add_funds,
      uri: STR_CONST.MENU_ITEMS.URI.add_funds,
    },
    {
      icon: CONST.WITHDRAW_FUNDS,
      id: STR_CONST.MENU_ITEMS.IDS.withdraw_funds,
      title: STR_CONST.MENU_ITEMS.TITLES.withdraw_funds,
      uri: STR_CONST.MENU_ITEMS.URI.withdraw_funds,
    },
    {
      icon: CONST.TRANSACTION_HISTORY,
      id: STR_CONST.MENU_ITEMS.IDS.transaction_history,
      title: STR_CONST.MENU_ITEMS.TITLES.transaction_history,
      uri: STR_CONST.MENU_ITEMS.URI.transaction_history,
    },
    {
      icon: CONST.TERM,
      id: STR_CONST.MENU_ITEMS.IDS.terms_condition,
      title: STR_CONST.MENU_ITEMS.TITLES.terms_condition,
      uri: STR_CONST.MENU_ITEMS.URI.terms_condition,
    },
    {
      icon: CONST.PRIVACY,
      id: STR_CONST.MENU_ITEMS.IDS.privacy_policy,
      title: STR_CONST.MENU_ITEMS.TITLES.privacy_policy,
      uri: STR_CONST.MENU_ITEMS.URI.privacy_policy,
    },
    {
      icon: CONST.ACCOUNT,
      id: STR_CONST.MENU_ITEMS.IDS.rules_scoring,
      title: STR_CONST.MENU_ITEMS.TITLES.rules_scoring,
      uri: STR_CONST.MENU_ITEMS.URI.rules_scoring,
    },
    {
      icon: CONST.CUP,
      id: STR_CONST.MENU_ITEMS.IDS.fair_play_commitment,
      title: STR_CONST.MENU_ITEMS.TITLES.fair_play_commitment,
      uri: STR_CONST.MENU_ITEMS.URI.fair_play_commitment,
    },
    {
      icon: CONST.GAME,
      id: STR_CONST.MENU_ITEMS.IDS.responsible_gaming,
      title: STR_CONST.MENU_ITEMS.TITLES.responsible_gaming,
      uri: STR_CONST.MENU_ITEMS.URI.responsible_gaming,
    },
    {
      icon: CONST.LOGOUTBG,
      id: STR_CONST.MENU_ITEMS.IDS.logout,
      title: STR_CONST.MENU_ITEMS.TITLES.logout,
      uri: STR_CONST.MENU_ITEMS.URI.logout,
    },
  ],
  settings: [
    {
      id: 0,
      title: 'My Profile',
      icon: 'user',
      iconFamily: 'AntDesign',
    },
    {
      id: 1,
      title: 'Notifications',
      icon: 'bells',
      iconFamily: 'AntDesign',
    },
    {
      id: 2,
      title: 'Contact Us',
      icon: 'contacts',
      iconFamily: 'AntDesign',
    },
    {
      id: 3,
      title: 'Log Out',
      icon: 'logout',
      iconFamily: 'AntDesign',
    },
  ],
  constestDate: [
    {
      id: 0,
      title: 'All Sunday Games',
      value: 'SG',
      subTitle: 'Compete from a slate of all Sunday Starts',
    },
    {
      id: 1,
      title: '1PM Starts',
      value: '1PM',
      subTitle: 'Compete in just the Sunday 1PM Starts',
    },
    {
      id: 2,
      title: '4PM Starts',
      value: '4PM',
      subTitle: 'Compete in just the Sunday 4PM Starts',
    },
    {
      id: 3,
      title: 'Thu | Sun | Mon Nightly Starts',
      value: 'NF',
      subTitle: 'Compete from a slate of Nightly Starts',
    },
  ],
  constestType: [
    {
      id: 0,
      title: 'featured',
      value: 'featured',
      subTitle: 'Compete in our Featured tournaments and win big cash prizes',
    },
    {
      id: 1,
      title: 'beginner',
      value: 'beginner',
      subTitle: 'Compete in our Beginner tournaments and win big cash prizes',
    },
    {
      id: 2,
      title: '50-50',
      value: 'fiftyfifty',
      subTitle: 'Compete against a field of users and half the field gets paid',
    },
    {
      id: 3,
      title: 'head-head',
      value: 'head2head',
      subTitle: 'Compete against 1 user and winner takes all',
    },
    {
      id: 4,
      title: 'sit n go',
      value: 'sitngo',
      subTitle: 'Compete against 6 players and top 2 gets paid',
    },
    {
      id: 5,
      title: 'All',
      value: 'all',
      subTitle: 'View All',
    },
  ],
  playerProfilePics: [
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/71.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/77.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/87.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/35.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/45.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/85.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/95.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/65.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/55.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/25.jpg',
    },
    {
      profile_image_url: 'https://randomuser.me/api/portraits/men/35.jpg',
    },
  ],
  sports: [
    {
      id: 0,
      sports_name: 'NFL',
      icon: Icons.NFL_ACTIVE_ICON,
      inactive_icon: Icons.NFL_INACTIVE_ICON,
    },
  ],
  list: [
    {
      id: 0,
      sports_name: 'NBA',
      views: '100k to 1st',
      entrants: '5,123/100k',
      total_entrants: '5,123',
      prizes: '4500',
      entry: '5',
      time: new Date(),
      icon: CONST.BALL,
      rank: '5',
      total: '5',
      dollar: '$95',
      position: '5th',
      isUsersEntry: true,
      name: 'dangerrangers',
    },
    {
      id: 1,
      sports_name: 'MLB',
      views: '100k to 1st',
      entrants: '5,200/100k',
      total_entrants: '5,200',
      prizes: '1200',
      entry: '2',
      time: new Date(),
      icon: CONST.MLB,
      rank: '2',
      total: '2',
      dollar: '$150',
      position: '2nd',
      isUsersEntry: false,
      name: 'Test User 1',
    },
    {
      id: 2,
      sports_name: 'NHL',
      views: '100k to 1st',
      entrants: '4,500/100k',
      total_entrants: '4,500',
      prizes: '17000',
      entry: '1',
      time: new Date(),
      icon: CONST.NHL,
      rank: '3',
      total: '2',
      dollar: '$110',
      position: '3rd',
      isUsersEntry: false,
      name: 'Test User 2',
    },
    {
      id: 3,
      sports_name: 'NFL',
      views: '100k to 1st',
      entrants: '4,220/100k',
      total_entrants: '4,220',
      prizes: '11000',
      entry: '5',
      time: new Date(),
      icon: CONST.NFL,
      rank: '8',
      total: '2',
      dollar: '$70',
      position: '8th',
      isUsersEntry: false,
      name: 'Test User 3',
    },
    {
      id: 4,
      sports_name: 'NFL',
      views: '100k to 1st',
      entrants: '6,000/100k',
      total_entrants: '6,000',
      prizes: '17000',
      entry: '10',
      time: new Date(),
      icon: CONST.NFL,
      rank: '9',
      total: '2',
      dollar: '$50',
      position: '9th',
      isUsersEntry: false,
      name: 'Test User 4',
    },
    {
      id: 5,
      sports_name: 'NBA',
      views: '100k to 1st',
      entrants: '4,000/100k',
      total_entrants: '4,000',
      prizes: '10000',
      entry: '7',
      time: new Date(),
      icon: CONST.BALL,
      rank: '4',
      total: '3',
      dollar: '$100',
      position: '4rth',
      isUsersEntry: false,
      name: 'Test User 5',
    },
    {
      id: 6,
      sports_name: 'NHL',
      views: '100k to 1st',
      entrants: '3,720/100k',
      total_entrants: '3,720',
      prizes: '3400',
      entry: '5',
      time: new Date(),
      icon: CONST.NHL,
      rank: '6',
      total: '2',
      dollar: '$90',
      position: '6th',
      isUsersEntry: false,
      name: 'Test User 6',
    },
    {
      id: 7,
      sports_name: 'MLB',
      views: '100k to 1st',
      entrants: '2,123/100k',
      total_entrants: '2,123',
      prizes: '4300',
      entry: '1',
      time: new Date(),
      icon: CONST.MLB,
      rank: '1',
      total: '2',
      dollar: '$200',
      position: '1st',
      isUsersEntry: false,
      name: 'Test User 7',
    },
    {
      id: 8,
      sports_name: 'NBA',
      views: '100k to 1st',
      entrants: '2,500/100k',
      total_entrants: '2,500',
      prizes: '7000',
      entry: '3',
      time: new Date(),
      icon: CONST.BALL,
      rank: '7',
      total: '3',
      dollar: '$75',
      position: '7th',
      isUsersEntry: false,
      name: 'Test User 8',
    },
  ],
  filterData: [
    {
      id: CONST.FILTER_OPTION_ID.SORTED_BY,
      type: CONST.SELECTION_TYPE.SINGLE,
      title: 'Sort By',
      subTitle: 'Recommended',
      data: [
        {
          id: CONST.SORTED_BY.RECOMMENDED,
          title: 'Recommended',
          isSelected: true,
        },
        {
          id: CONST.SORTED_BY.ENTRY_FEE_HIGH_TO_LOW,
          title: 'Entry Fee - High to Low',
          isSelected: false,
          value: 'entryFee:desc',
        },
        {
          id: CONST.SORTED_BY.ENTRY_FEE_LOW_TO_HIGH,
          title: 'Entry Fee - Low to High',
          isSelected: false,
          value: 'entryFee:asc',
        },
        {
          id: CONST.SORTED_BY.ENTRIES_HIGH_TO_LOW,
          title: 'Entries - High to Low',
          isSelected: false,
          value: 'totalEntries:desc',
        },
        {
          id: CONST.SORTED_BY.ENTRIES_LOW_TO_HIGH,
          title: 'Entries - Low to High',
          isSelected: false,
          value: 'totalEntries:asc',
        },
        {
          id: CONST.SORTED_BY.TOTAL_PRIZES_HIGH_TO_LOW,
          title: 'Total Prizes - High to Low',
          isSelected: false,
          value: 'prizePool:desc',
        },
        {
          id: CONST.SORTED_BY.TOTAL_PRIZES_LOW_TO_HIGH,
          title: 'Total Prizes - Low to High',
          isSelected: false,
          value: 'prizePool:asc',
        },
        {
          id: CONST.SORTED_BY.CONTEST_NAME_Z_TO_A,
          title: 'Contest Name - Z to A',
          isSelected: false,
          value: 'title:desc',
        },
        {
          id: CONST.SORTED_BY.CONTEST_NAME_A_TO_Z,
          title: 'Contest Name - A to Z',
          isSelected: false,
          value: 'title:asc',
        },
      ],
      selected: false,
      filterKey: 'sortBy',
    },
    {
      id: CONST.FILTER_OPTION_ID.CONTEST_TYPE,
      type: CONST.SELECTION_TYPE.SINGLE,
      title: 'Contest Type',
      subTitle: 'All',
      data: [
        {
          title: 'All',
          isSelected: true,
        },
        {
          title: 'Beginner',
          isSelected: false,
          value: 'beginner',
        },
        {
          title: 'Featured',
          isSelected: false,
          value: 'featured',
        },
        {
          title: 'Head to Head',
          isSelected: false,
          value: 'head2head',
        },
        {
          title: '50-50',
          isSelected: false,
          value: 'fiftyfifty',
        },
        {
          title: 'Sit N Go',
          isSelected: false,
          value: 'sitngo',
        },
      ],
      selected: false,
      filterKey: 'tournamentType',
    },
    {
      id: CONST.FILTER_OPTION_ID.MULTI_ENTRY_LIMIT,
      type: CONST.SELECTION_TYPE.SINGLE,
      title: 'Multi-Entry Limit',
      subTitle: 'All',
      data: [
        {
          title: 'All',
          isSelected: true,
        },
        {
          title: 'Single Entry',
          isSelected: false,
          minValue: 1,
          maxValue: 1,
        },
        {
          title: '2-3 Entry Max',
          isSelected: false,
          minValue: 2,
          maxValue: 3,
        },
        {
          title: '4-10 Entry Max',
          isSelected: false,
          minValue: 4,
          maxValue: 10,
        },
        {
          title: '11-20 Entry Max',
          isSelected: false,
          minValue: 11,
          maxValue: 20,
        },
        {
          title: '21-149 Entry Max',
          isSelected: false,
          minValue: 21,
          maxValue: 149,
        },
        {
          title: '150 Entry Max',
          isSelected: false,
          minValue: 150,
          maxValue: 150,
        },
      ],
      selected: false,
      filterMinKey: 'maxPerPlayerGte',
      filterMaxKey: 'maxPerPlayerLte',
    },
    {
      id: CONST.FILTER_OPTION_ID.GUARANTEED_STATUS,
      type: CONST.SELECTION_TYPE.SINGLE,
      title: 'Guaranteed Status',
      subTitle: 'All',
      data: [
        {
          title: 'All',
          isSelected: true,
        },
        {
          title: 'Guaranteed',
          isSelected: false,
        },
        {
          title: 'Non-Guaranteed',
          isSelected: false,
        },
      ],
      selected: false,
      filterKey: 'guaranteedStatus',
    },
  ],
  inputFields: [
    {
      type: 1,
      title: 'Entry Fee',
      enabled: false,
      minValue: 0,
      maxValue: 0,
    },
    {
      type: 1,
      title: 'Total Prize Pool',
      enabled: false,
      minValue: 0,
      maxValue: 0,
    },
    {
      type: 1,
      title: 'Field Size',
      enabled: false,
      minValue: 0,
      maxValue: 0,
    },
  ],
  paidValues: ['Free', '$2', '$25', '$200', '$20,000', '$1'],
  userList: [
    {
      id: 0,
      entrants: '5,123/100k',
      prizes: '200',
      entry: '5',
      icon: CONST.DEFAULT,
      name: 'dangerrangers',
      rank: '1',
      isUsersEntry: true,
      dollar: '$0',
    },
    {
      id: 1,
      entrants: '5,123/100k',
      prizes: '150',
      entry: '5',
      icon: CONST.DEFAULT,
      name: 'Test User 1',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
    {
      id: 2,
      entrants: '5,123/100k',
      prizes: '110',
      entry: '5',
      icon: CONST.DEFAULT,
      name: 'Test User 2',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
    {
      id: 3,
      entrants: '5,123/100k',
      prizes: '100',
      entry: '7',
      icon: CONST.DEFAULT,
      name: 'Test User 3',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
    {
      id: 4,
      entrants: '5,123/100k',
      prizes: '98',
      entry: '5',
      icon: CONST.DEFAULT,
      name: 'Test User 4',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
    {
      id: 5,
      entrants: '5,123/100k',
      prizes: '95',
      entry: '8',
      icon: CONST.DEFAULT,
      name: 'Test User 5',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
    {
      id: 6,
      entrants: '5,123/100k',
      prizes: '90',
      entry: '1',
      icon: CONST.DEFAULT,
      name: 'Test User 6',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
    {
      id: 7,
      entrants: '5,123/100k',
      prizes: '75',
      entry: '8',
      icon: CONST.DEFAULT,
      name: 'Test User 7',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
    {
      id: 8,
      entrants: '5,123/100k',
      prizes: '70',
      entry: '5',
      icon: CONST.DEFAULT,
      name: 'Testing',
      rank: '1',
      isUsersEntry: false,
      dollar: '$0',
    },
  ],
  locationList:
    Platform.OS === 'android'
      ? [
          {
            icon: CONST.ANDROID_OPEN_SETTINGS,
            title: '“Open Settings” below',
          },
          {
            icon: CONST.ANDROID_TAP_PERMISSIONS,
            title: 'Tap “Permissions”',
          },
          {
            icon: CONST.ANDROID_ENABLE_LOCATION,
            title: 'Enable Location Settings',
          },
        ]
      : [
          {
            icon: CONST.SETTING_LOGO,
            title: 'Open Settings',
          },
          {
            icon: CONST.DREAMPICK_LOGO,
            title: 'Tap ‘DreamPick App Icon’',
          },
          {
            icon: CONST.TAP_LOCATION_LOGO,
            title: 'Tap ‘Location’',
          },
          {
            icon: CONST.LOCATION_CHECK_LOGO,
            title: 'Tap ‘While Using the App’',
          },
        ],
  jointMenuOptions: [
    {
      id: 0,
      isSelect: false,
      icon: CONST.LIST,
      text: 'Entrants List',
    },
    {
      id: 1,
      isSelect: false,
      icon: CONST.INFORMATION,
      text: 'Contest Details',
    },
    {
      id: 2,
      isSelect: false,
      icon: CONST.SCORING,
      text: 'Scoring Rules',
    },
    {
      id: 3,
      isSelect: false,
      icon: CONST.PAYOUT,
      text: 'Payout Structure',
    },
    {
      id: 4,
      isSelect: false,
      icon: CONST.CUP_WHITE,
      text: STR_CONST.fairPlayCommitment,
    },
  ],
  guaranteedEyeIconOptions: [
    {
      icon: CONST.GUARANTEED_ICON,
      headerText: STR_CONST.GUARANTEED_HEADER_TEXT,
      description: STR_CONST.GUARANTEED_DESCRIPTION_TEXT,
    },
  ],
  generalEyeIconOptions: [
    {
      icon: CONST.SELECTED_RADIO,
      headerText: STR_CONST.pp1Text,
      description: STR_CONST.pps,
      divider: true,
    },
    {
      icon: CONST.RESERVEICON,
      headerText: STR_CONST.pp2Text,
      description: STR_CONST.ppj,
    },
  ],
  playerRecordsEyeIconOptions: [
    {
      icon: CONST.FLAMEICON,
      headerText: STR_CONST.flameText,
      description: STR_CONST.ht,
      divider: true,
    },
    {
      icon: CONST.SNOWICON,
      headerText: STR_CONST.coldText,
      description: STR_CONST.ct,
      divider: true,
    },
    {
      icon: CONST.TICKICON,
      headerText: STR_CONST.dtickText,
      description: STR_CONST.ppt,
    },
  ],
  playersData: {
    team_id: 10000016,
    players: [
      {
        actualFppg: 16,
        actualUsed: true,
        fppg: 19.33,
        name: 'Lucas Giolito',
        position: 'SP',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10005879.png',
        playerType: 'starter',
      },
      {
        actualFppg: 25,
        actualUsed: true,
        fppg: 8.95,
        name: 'Luis Robert',
        position: 'RF',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10008206.png',
        playerType: 'starter',
      },
      {
        actualFppg: 8,
        actualUsed: true,
        fppg: 8.85,
        name: 'José Abreu',
        position: '1B',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000258.png',
        playerType: 'starter',
      },
      {
        actualFppg: 5,
        actualUsed: true,
        fppg: 8.46,
        name: 'Eloy Jiménez',
        position: 'LF',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10006154.png',
        playerType: 'starter',
      },
      {
        actualFppg: 8,
        actualUsed: true,
        fppg: 7.89,
        name: 'César Hernández',
        position: '2B',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000955.png',
        playerType: 'starter',
      },
      {
        actualFppg: 0,
        actualUsed: false,
        fppg: 7.47,
        name: 'Andrew Vaughn',
        position: 'CF',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10010464.png',
        playerType: 'reserve',
      },
      {
        actualFppg: 5,
        actualUsed: false,
        fppg: 7.38,
        name: 'Yasmani Grandal',
        position: 'C',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000633.png',
        playerType: 'reserve',
      },
    ],
  },
  accordianData: {
    selectedTeamName: 'GB',
    selectedTeamPoints: 30,
    competingTeamName: 'PHI',
    competingTeamPoints: 16,
    bonus: -65,
    performance: -199.26,
    details: {},
  },
  liveLeaderboardComparisonData: [
    {
      myComparisionDetails: {
        GlobalGameID: 17702,
        AwayTeam: 'BUF',
        DateTime: '2021-09-19T17:00:00.000Z',
        GlobalAwayTeamID: 4,
        GlobalHomeTeamID: 19,
        HomeTeam: 'MIA',
        id: '613e4e36f3e54dc34a9327e8',
        HomeTeamFantasyPoints: 86.18,
        AwayTeamFantasyPoints: 100.41,
        selectedTeamId: 4,
        booster: 61,
        bonusPoints: '0.00',
        penaltyPoints: '41.61',
        home_score: 0,
        away_score: 35,
        estimateFantasyPoints: 100.41,
        finalFantasyPoints: 79.86,
        myGameScore: 38.25294,
      },
      opponentComparisionDetails: {
        GlobalGameID: 17700,
        AwayTeam: 'HOU',
        DateTime: '2021-09-19T17:00:00.000Z',
        GlobalAwayTeamID: 13,
        GlobalHomeTeamID: 8,
        HomeTeam: 'CLE',
        id: '613e4e36f3e54dc34a9327e5',
        HomeTeamFantasyPoints: 99.91,
        AwayTeamFantasyPoints: 69.54,
        selectedOppTeamId: 8,
        oppBooster: 70,
        oppBonusPoints: '0.00',
        oppPenaltyPoints: '59.00',
        homeOpp_score: 31,
        awayOpp_score: 21,
        estimateOppFantasyPoints: 99.91,
        finalOppFantasyPoints: 63.32,
        oppGameScore: 4.318424000000005,
      },
    },
    {
      myComparisionDetails: {
        GlobalGameID: 17710,
        AwayTeam: 'DAL',
        DateTime: '2021-09-19T20:25:00.000Z',
        GlobalAwayTeamID: 9,
        GlobalHomeTeamID: 29,
        HomeTeam: 'LAC',
        id: '613e4e36f3e54dc34a9327ee',
        HomeTeamFantasyPoints: 101.92,
        AwayTeamFantasyPoints: 103.02,
        selectedTeamId: 9,
        booster: 50,
        bonusPoints: '0.00',
        penaltyPoints: '18.17',
        home_score: 17,
        away_score: 20,
        estimateFantasyPoints: 103.02,
        finalFantasyPoints: 93.28,
        myGameScore: 75.10905600000001,
      },
      opponentComparisionDetails: {
        GlobalGameID: 17710,
        AwayTeam: 'DAL',
        DateTime: '2021-09-19T20:25:00.000Z',
        GlobalAwayTeamID: 9,
        GlobalHomeTeamID: 29,
        HomeTeam: 'LAC',
        id: '613e4e36f3e54dc34a9327ee',
        HomeTeamFantasyPoints: 101.92,
        AwayTeamFantasyPoints: 103.02,
        selectedOppTeamId: 9,
        oppBooster: 50,
        oppBonusPoints: '0.00',
        oppPenaltyPoints: '18.17',
        homeOpp_score: 17,
        awayOpp_score: 20,
        estimateOppFantasyPoints: 103.02,
        finalOppFantasyPoints: 93.28,
        oppGameScore: 75.10905600000001,
      },
    },
    {
      myComparisionDetails: {
        GlobalGameID: 17713,
        AwayTeam: 'DET',
        DateTime: '2021-09-21T00:15:00.000Z',
        GlobalAwayTeamID: 11,
        GlobalHomeTeamID: 12,
        HomeTeam: 'GB',
        id: '613e4e36f3e54dc34a9327f2',
        HomeTeamFantasyPoints: 107.16,
        AwayTeamFantasyPoints: 83.22,
        selectedTeamId: 12,
        booster: 58,
        bonusPoints: '66.24',
        penaltyPoints: '0.00',
        home_score: 35,
        away_score: 17,
        estimateFantasyPoints: 107.16,
        finalFantasyPoints: 114.2,
        myGameScore: 180.436,
      },
      opponentComparisionDetails: {
        GlobalGameID: 17713,
        AwayTeam: 'DET',
        DateTime: '2021-09-21T00:15:00.000Z',
        GlobalAwayTeamID: 11,
        GlobalHomeTeamID: 12,
        HomeTeam: 'GB',
        id: '613e4e36f3e54dc34a9327f2',
        HomeTeamFantasyPoints: 107.16,
        AwayTeamFantasyPoints: 83.22,
        selectedOppTeamId: 11,
        oppBooster: 45,
        oppBonusPoints: '40.70',
        oppPenaltyPoints: '0.00',
        homeOpp_score: 35,
        awayOpp_score: 17,
        estimateOppFantasyPoints: 83.22,
        finalOppFantasyPoints: 90.44,
        oppGameScore: 131.138,
      },
    },
  ],
  dummyLeaderBoardData: {
    id: '614701b8a369f8a2a9d1300e',
    startsAt: '2021-09-19T17:00:00.000Z',
    remainingPlayers: 0,
    userScores: [
      {
        entryScore: 293.797996,
        selections: [
          {
            GlobalGameID: 17702,
            GlobalTeamID: 4,
            booster: 61,
            bonusPercentage: 61,
            bonusPoints: 0,
            gameScore: 38.25294,
            penaltyPoints: 41.60706,
          },
          {
            GlobalGameID: 17710,
            GlobalTeamID: 9,
            booster: 50,
            bonusPercentage: 50,
            bonusPoints: 0,
            gameScore: 75.10905600000001,
            penaltyPoints: 18.17094399999999,
          },
          {
            GlobalGameID: 17713,
            GlobalTeamID: 12,
            booster: 58,
            bonusPercentage: 58,
            bonusPoints: 66.236,
            gameScore: 180.436,
            penaltyPoints: 0,
          },
        ],
        rank: 1,
      },
      {
        entryScore: 210.56548000000004,
        selections: [
          {
            GlobalGameID: 17700,
            GlobalTeamID: 8,
            booster: 70,
            bonusPercentage: 70,
            bonusPoints: 0,
            gameScore: 4.318424000000005,
            penaltyPoints: 59.00157599999999,
          },
          {
            GlobalGameID: 17710,
            GlobalTeamID: 9,
            booster: 50,
            bonusPercentage: 50,
            bonusPoints: 0,
            gameScore: 75.10905600000001,
            penaltyPoints: 18.17094399999999,
          },
          {
            GlobalGameID: 17713,
            GlobalTeamID: 11,
            booster: 45,
            bonusPercentage: 45,
            bonusPoints: 40.69800000000001,
            gameScore: 131.138,
            penaltyPoints: 0,
          },
        ],
        rank: 2,
      },
    ],
    teamScores: [
      {
        GlobalGameID: 17703,
        GlobalTeamID: 24,
        estimateFantasyPoints: 70.67,
        finalFantasyPoints: 33,
        score: 6,
      },
      {
        GlobalGameID: 17703,
        GlobalTeamID: 21,
        estimateFantasyPoints: 89.38,
        finalFantasyPoints: 80.24,
        score: 25,
      },
      {
        GlobalGameID: 17701,
        GlobalTeamID: 14,
        estimateFantasyPoints: 83.46000000000001,
        finalFantasyPoints: 94.38,
        score: 24,
      },
      {
        GlobalGameID: 17701,
        GlobalTeamID: 32,
        estimateFantasyPoints: 102.65,
        finalFantasyPoints: 100.42,
        score: 27,
      },
      {
        GlobalGameID: 17704,
        GlobalTeamID: 26,
        estimateFantasyPoints: 90.28,
        finalFantasyPoints: 61.5,
        score: 11,
      },
      {
        GlobalGameID: 17704,
        GlobalTeamID: 31,
        estimateFantasyPoints: 98.53,
        finalFantasyPoints: 68.06,
        score: 17,
      },
      {
        GlobalGameID: 17702,
        GlobalTeamID: 19,
        estimateFantasyPoints: 86.18,
        finalFantasyPoints: 42.92,
        score: 0,
      },
      {
        GlobalGameID: 17702,
        GlobalTeamID: 4,
        estimateFantasyPoints: 100.41,
        finalFantasyPoints: 79.86,
        score: 35,
      },
      {
        GlobalGameID: 17700,
        GlobalTeamID: 8,
        estimateFantasyPoints: 99.91,
        finalFantasyPoints: 63.32,
        score: 31,
      },
      {
        GlobalGameID: 17700,
        GlobalTeamID: 13,
        estimateFantasyPoints: 69.54,
        finalFantasyPoints: 62.8,
        score: 21,
      },
      {
        GlobalGameID: 17699,
        GlobalTeamID: 6,
        estimateFantasyPoints: 90.13,
        finalFantasyPoints: 54.04,
        score: 20,
      },
      {
        GlobalGameID: 17699,
        GlobalTeamID: 7,
        estimateFantasyPoints: 93.38,
        finalFantasyPoints: 75.48,
        score: 17,
      },
      {
        GlobalGameID: 17705,
        GlobalTeamID: 28,
        estimateFantasyPoints: 99.28,
        finalFantasyPoints: 97.1,
        score: 17,
      },
      {
        GlobalGameID: 17705,
        GlobalTeamID: 25,
        estimateFantasyPoints: 87.88,
        finalFantasyPoints: 112.58,
        score: 26,
      },
      {
        GlobalGameID: 17706,
        GlobalTeamID: 5,
        estimateFantasyPoints: 93.86,
        finalFantasyPoints: 100.2,
        score: 26,
      },
      {
        GlobalGameID: 17706,
        GlobalTeamID: 22,
        estimateFantasyPoints: 88.61,
        finalFantasyPoints: 27.14,
        score: 7,
      },
      {
        GlobalGameID: 17708,
        GlobalTeamID: 1,
        estimateFantasyPoints: 103.71,
        finalFantasyPoints: 130.9,
        score: 34,
      },
      {
        GlobalGameID: 17708,
        GlobalTeamID: 20,
        estimateFantasyPoints: 98.69,
        finalFantasyPoints: 119.86,
        score: 33,
      },
      {
        GlobalGameID: 17707,
        GlobalTeamID: 15,
        estimateFantasyPoints: 85.78,
        finalFantasyPoints: 45.42,
        score: 13,
      },
      {
        GlobalGameID: 17707,
        GlobalTeamID: 10,
        estimateFantasyPoints: 96.59,
        finalFantasyPoints: 109.92,
        score: 23,
      },
      {
        GlobalGameID: 17711,
        GlobalTeamID: 30,
        estimateFantasyPoints: 103.3,
        finalFantasyPoints: 94.82,
        score: 30,
      },
      {
        GlobalGameID: 17711,
        GlobalTeamID: 34,
        estimateFantasyPoints: 97.35,
        finalFantasyPoints: 117.58,
        score: 33,
      },
      {
        GlobalGameID: 17710,
        GlobalTeamID: 29,
        estimateFantasyPoints: 101.92,
        finalFantasyPoints: 102.92,
        score: 17,
      },
      {
        GlobalGameID: 17710,
        GlobalTeamID: 9,
        estimateFantasyPoints: 103.02,
        finalFantasyPoints: 93.28,
        score: 20,
      },
      {
        GlobalGameID: 17709,
        GlobalTeamID: 33,
        estimateFantasyPoints: 114.17,
        finalFantasyPoints: 116.14,
        score: 48,
      },
      {
        GlobalGameID: 17709,
        GlobalTeamID: 2,
        estimateFantasyPoints: 89.53,
        finalFantasyPoints: 105.5,
        score: 25,
      },
      {
        GlobalGameID: 17712,
        GlobalTeamID: 3,
        estimateFantasyPoints: 93.09,
        finalFantasyPoints: 116.56,
        score: 36,
      },
      {
        GlobalGameID: 17712,
        GlobalTeamID: 16,
        estimateFantasyPoints: 112.31,
        finalFantasyPoints: 99.32,
        score: 35,
      },
      {
        GlobalGameID: 17713,
        GlobalTeamID: 12,
        estimateFantasyPoints: 107.16,
        finalFantasyPoints: 114.2,
        score: 35,
      },
      {
        GlobalGameID: 17713,
        GlobalTeamID: 11,
        estimateFantasyPoints: 83.22,
        finalFantasyPoints: 90.44,
        score: 17,
      },
    ],
    createdAt: '2021-09-19T09:24:08.288Z',
    updatedAt: '2021-09-23T10:14:35.135Z',
  },
  otherDetials: {
    contestDetail: {
      username: 'ajsince19862',
      rank: 1,
      prize: 20,
      score: '129.46',
      selection_id: '615376208ab2ac002881d65d',
      profilePicture:
        'https://dream-pick-user-profile-pictures.s3.amazonaws.com/72455034576.jpg',
    },
    myEntrySum: 340.44,
    opponentEntrySum: 420.43,
    myDetails: {
      username: 'ajsince19862',
      rank: 5,
      prize: 7,
      score: '64.90',
      selection_id: '6153764a8ab2ac002881d65f',
      profilePicture:
        'https://dream-pick-user-profile-pictures.s3.amazonaws.com/72455034576.jpg',
    },
  },

  myContestDetails: {
    entryScore: 249.2352,
    modifiedAt: '2021-10-15T05:51:30.392Z',
    prize: 12,
    profilePicture:
      'https://dream-pick-user-profile-pictures.s3.amazonaws.com/72455034576.jpg',
    rank: 2,
    tournamentId: '6167e95eda84b7002985c5cd',
    username: 'ajsince19862',
    selections: [
      {
        GlobalGameID: 30017229,
        GlobalTeamID: 10000025,
        booster: 42,
        selectedPoints: 142,
        actualPoint: 132,
        bonusPercentage: 42,
        bonusPoints: 20.915999999999997,
        gameScore: 70.716,
        penaltyPoints: 0,
        roasters: [
          {
            actualFppg: 15.8,
            actualUsed: true,
            fppg: 16.66,
            name: 'Nathan Eovaldi',
            position: 'SP',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000837.png',
            playerType: 'starter',
          },
          {
            actualFppg: 18,
            actualUsed: true,
            fppg: 8.4,
            name: 'Xander Bogaerts',
            position: 'SS',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000165.png',
            playerType: 'starter',
          },
          {
            actualFppg: 7,
            actualUsed: true,
            fppg: 8.19,
            name: 'Kike Hernández',
            position: 'CF',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000637.png',
            playerType: 'starter',
          },
          {
            actualFppg: 7,
            actualUsed: true,
            fppg: 7.93,
            name: 'Rafael Devers',
            position: '3B',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10005751.png',
            playerType: 'starter',
          },
          {
            actualFppg: 2,
            actualUsed: true,
            fppg: 7.91,
            name: 'J.D. Martinez',
            position: 'LF',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000453.png',
            playerType: 'starter',
          },
          {
            actualFppg: 2,
            actualUsed: false,
            fppg: 7.72,
            name: 'Bobby Dalbec',
            position: '1B',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10007062.png',
            playerType: 'reserve',
          },
          {
            actualFppg: 0,
            actualUsed: false,
            fppg: 7.21,
            name: 'Christian Vázquez',
            position: 'C',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000164.png',
            playerType: 'reserve',
          },
        ],
      },
      {
        GlobalGameID: 30017230,
        GlobalTeamID: 10000001,
        booster: 46,
        selectedPoints: 142,
        actualPoint: 132,
        bonusPercentage: 46,
        bonusPoints: 26.932999999999993,
        gameScore: 85.48299999999999,
        penaltyPoints: 0,
        roasters: [
          {
            actualFppg: 15.8,
            actualUsed: true,
            fppg: 16.66,
            name: 'Nathan Eovaldi',
            position: 'SP',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000837.png',
            playerType: 'starter',
          },
          {
            actualFppg: 18,
            actualUsed: true,
            fppg: 8.4,
            name: 'Xander Bogaerts',
            position: 'SS',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000165.png',
            playerType: 'starter',
          },
          {
            actualFppg: 7,
            actualUsed: true,
            fppg: 8.19,
            name: 'Kike Hernández',
            position: 'CF',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000637.png',
            playerType: 'starter',
          },
          {
            actualFppg: 7,
            actualUsed: true,
            fppg: 7.93,
            name: 'Rafael Devers',
            position: '3B',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10005751.png',
            playerType: 'starter',
          },
          {
            actualFppg: 2,
            actualUsed: true,
            fppg: 7.91,
            name: 'J.D. Martinez',
            position: 'LF',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000453.png',
            playerType: 'starter',
          },
          {
            actualFppg: 2,
            actualUsed: false,
            fppg: 7.72,
            name: 'Bobby Dalbec',
            position: '1B',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10007062.png',
            playerType: 'reserve',
          },
          {
            actualFppg: 0,
            actualUsed: false,
            fppg: 7.21,
            name: 'Christian Vázquez',
            position: 'C',
            photoUrl:
              'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/mlb/low-res/10000164.png',
            playerType: 'reserve',
          },
        ],
      },
    ],
  },
  othersDetailsPlayerList: [
    {
      myComparisionDetails: {
        actualFppg: 18.98,
        actualUsed: true,
        fppg: 25.27,
        name: 'Tom Brady',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/4314.png',
        playerType: 'starter',
        position: 'QB',
      },
      opponentComparisionDetails: {
        actualFppg: 26,
        actualUsed: true,
        fppg: 22.26,
        name: 'Jalen Hurts',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21831.png',
        playerType: 'starter',
        position: 'QB',
      },
    },
    {
      myComparisionDetails: {
        actualFppg: 9.3,
        actualUsed: true,
        fppg: 16.3,
        name: 'Chris Godwin',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18880.png',
        playerType: 'starter',
        position: 'WR',
      },
      opponentComparisionDetails: {
        actualFppg: 5.1,
        actualUsed: true,
        fppg: 14.24,
        name: 'DeVonta Smith',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21687.png',
        playerType: 'starter',
        position: 'WR',
      },
    },
    {
      myComparisionDetails: {
        actualFppg: 4.7,
        actualUsed: true,
        fppg: 16.1,
        name: 'Mike Evans',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/16597.png',
        playerType: 'starter',
        position: 'WR',
      },
      opponentComparisionDetails: {
        actualFppg: 8.6,
        actualUsed: true,
        fppg: 11.65,
        name: 'Miles Sanders',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/20933.png',
        playerType: 'starter',
        position: 'RB',
      },
    },
    {
      myComparisionDetails: {
        actualFppg: 30.7,
        actualUsed: true,
        fppg: 14.02,
        name: 'Leonard Fournette',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/18803.png',
        playerType: 'starter',
        position: 'RB',
      },
      opponentComparisionDetails: {
        actualFppg: 12.9,
        actualUsed: true,
        fppg: 9.53,
        name: 'Zach Ertz',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14856.png',
        playerType: 'starter',
        position: 'TE',
        reason: 'Injured',
      },
    },
    {
      myComparisionDetails: {
        actualFppg: 24.3,
        actualUsed: true,
        fppg: 13.88,
        name: 'Antonio Brown',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/11056.png',
        playerType: 'starter',
        position: 'WR',
      },
      opponentComparisionDetails: {
        actualFppg: 0,
        actualUsed: true,
        fppg: 8.95,
        name: 'Jalen Reagor',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21686.png',
        playerType: 'starter',
        position: 'WR',
      },
    },
    {
      myComparisionDetails: {
        actualFppg: 4,
        actualUsed: true,
        fppg: 9.56,
        name: 'Ryan Succop',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/8750.png',
        playerType: 'starter',
        position: 'K',
      },
      opponentComparisionDetails: {
        actualFppg: 1.1,
        actualUsed: true,
        fppg: 8.47,
        name: 'Kenneth Gainwell',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/22562.png',
        playerType: 'starter',
        position: 'RB',
      },
    },
    {
      myComparisionDetails: {
        actualFppg: 2.4,
        actualUsed: true,
        fppg: 5.86,
        name: 'Giovani Bernard',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/14916.png',
        playerType: 'starter',
        position: 'RB',
      },
      opponentComparisionDetails: {
        actualFppg: 2,
        actualUsed: true,
        fppg: 7.74,
        name: 'Jake Elliott',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19041.png',
        playerType: 'starter',
        position: 'K',
      },
    },
    {
      myComparisionDetails: {
        actualFppg: 3.9,
        actualUsed: true,
        fppg: 5.77,
        name: 'Ronald Jones II',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/19861.png',
        playerType: 'starter',
        position: 'RB',
      },
      opponentComparisionDetails: {
        actualFppg: 9.4,
        actualUsed: true,
        fppg: 6.82,
        name: 'Quez Watkins',
        photoUrl:
          'https://s3-us-west-2.amazonaws.com/static.fantasydata.com/headshots/nfl/low-res/21957.png',
        playerType: 'starter',
        position: 'WR',
      },
    },
  ],
  contestTypeFilter: [
    {
      title: 'All',
      isSelected: true,
      value: 'all',
    },
    {
      title: 'Head to Head',
      isSelected: false,
      value: 'head2head',
    },
    {
      title: '50-50',
      isSelected: false,
      value: 'fiftyfifty',
    },
    {
      title: 'Sit N Go',
      isSelected: false,
      value: 'sitngo',
    },
  ],
  joinContestMenuOptions: [
    'Entrants List',
    'Contest Details',
    'Scoring Rules',
    'Payout Structure',
    STR_CONST.fairPlayCommitment,
    'Cancel',
  ],
  tournamentMenuOptions: [
    'ENTER',
    'MY ENTRIES',
    'ENTRANTS',
    'DETAILS',
    'RULES',
  ],
  myContestDetailsMenuOptions: ['MY ENTRIES', 'ENTRANTS', 'DETAILS', 'RULES'],
  myContestLiveDetailsMenuOptions: [
    'MY ENTRIES',
    'STANDINGS',
    'DETAILS',
    'RULES',
  ],

  rulesData: {
    passingYards: 1,
    threeHandredPassingYards: 3,
    passingTD: 4,
    interceptions: -1,
    rushingYards: 3,
    oneHandredPassingYards: 4,
    rushingTD: -3,
    receivingYards: 2,
    oneHandredReceivingYard: 5,
    reception: 8,
    receivingTD: 5,
    fumbleLost: 0,
  },
  payoutStucture: [{maxRank: 1, minRank: 1, prizeAmount: 18}],

  myEntriesData: [
    {
      joinedTournamentItem: {
        entryScore: 0,
        id: '61e6fddea09d620028d6c27b',
        paid: false,
        prize: 0,
        refunded: false,
        selections: [Array],
      },
      prize: '0',
      profilePicture:
        'https://dream-pick-user-profile-pictures.s3.amazonaws.com/627813177746.png',
      rank: '1',
      score: '0',
      username: 'dangerrangers999',
    },
  ],
  listData: [
    {
      prize: undefined,
      profilePicture:
        'https://dream-pick-user-profile-pictures.s3.amazonaws.com/627813177746.png',
      rank: undefined,
      score: 'NaN',
      selection_id: undefined,
      username: 'dangerrangers999',
    },
  ],
};
